language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # PyPy versions
  # - "pypy"
  # - "pypy"  # PyPy2 2.5.0
  # - "pypy3" # Pypy3 2.4.0
  # - "pypy-5.3.1"
# command to install dependencies
install:
  - cd Treasuregram
  - pip install -U pip
  - pip install -r requirements.txt
  - pip freeze
  - python3 manage.py makemigrations
  - python3 manage.py migrate
# command to run tests
# script: pytest
